### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by nguyenpbui** [sStonemason/RET-CLIP#6]
Dear authors, big congrats on your accepted paper!

I have a question about whether the pre-training dataset will be released or what I should do to access that dataset.

Best regards.

**Comment by sStonemason** [comment]
Thank you for your support of our work!
Our pre-training dataset is derived from real clinical scenarios and involves agreements with hospitals, so it remains private and is not available for the time being. Hope to get your understanding. We will let you know if there is an update on the dataset being made public.

**Comment by sStonemason** [comment]
Thank you for your support of our work!

Our pre-training dataset is derived from real clinical scenarios and involves agreements with hospitals, so it remains private and is not available for the time being. Hope to get your understanding. We will let you know if there is an update on the dataset being made public.

**Comment by nguyenpbui** [comment]
Thank you for your information.
